### PR TITLE
Fix/dog texture

### PR DESCRIPTION
**Pull request by Dan-Abr**
The dog's material was missing, I added it back.

### CODE REVIEW

**Comment by rummanwaqar** [comment]
@Dan-Abr you seem to be deleting three files in this PR? Can you double check that you aren't accidently deleting something imp?

**Comment by ndvo** [comment]
:D 
@Dan-Abr now the player character is naked!

**Comment by ndvo** [comment]
@Dan-Abr I merged this branch into mine. it should be fixed there.

**Comment by Dan-Abr** [comment]
Lol, @rummanwaqar, usually I delete the main scene after duplicating it to avoid my first mistake of metafiles being overwritten

**Comment by rummanwaqar** [comment]
@Dan-Abr hmm, okay. Just checking to make sure it wasn't accidental.

**Review by ndvo — APPROVED** [review]

**Review by rummanwaqar — APPROVED** [review]

**Review by rummanwaqar — APPROVED** [review]
I had to resolve a conflict after I merged Ben's PR but it still looks good

**Pull request merged**
