### PR TITLE
Fix/hold only one weapon

### PR DESCRIPTION
**Pull request by ndvo**
- Attack with left click
- Switch weapon with right click
- Drop weapon with long right click 
- Tags changed:
    - Weapon -> Range
    - WeaponMelee -> Melee

### CODE REVIEW

**Comment by Dan-Abr** [comment]
For me, changing weapons on space-button doesn't work when I have the gun as a weapon (the gun keeps being the main weapon).
Also, when I'm dropping the gun (long-space), it stays as the main weapon while its icon disappears from the inventory.
Also it seems like the death animation of the player is not triggering.

**Review by Dan-Abr — COMMENTED** [review]
For me, changing weapons on space-button doesn't work when I have the gun as a weapon (the gun keeps being the main weapon).
Also, when I'm dropping the gun (long-space), it stays as the main weapon while its icon disappears from the inventory.
Also it seems like the death animation of the player is not triggering.

**Comment by ndvo** [comment]
It seems the issue of the dropped gun only happens if the gun was never used.

**Comment by ndvo** [comment]
> For me, changing weapons on space-button doesn't work when I have the gun as a weapon (the gun keeps being the main weapon).
> Also, when I'm dropping the gun (long-space), it stays as the main weapon while its icon disappears from the inventory.
> Also it seems like the death animation of the player is not triggering.

@Dan-Abr I believe this issue is fixed now.

**Review by Dan-Abr — COMMENTED** [review]
Still can't change weapon - when I pickup the gun it sticks with shooting even when I have the knife

**Comment by ndvo** [comment]
Well, can you confirm that you are using the right button to attack with the knife?
Here is a more complete of the behaviour:

Player should use a Range Weapon to attack when the left click button is triggered. This switches to the range weapon automatically if one is available.
Player should use a Melee Weapon to attack when the right button is triggered. This switches to the melee weapon automatically if one is available.

Perhaps this behaviour is too counter-intuitive...

**Comment by ndvo** [comment]
We could perhaps use the right click to switch weapons, drop the use of the space and use always the left click for both melee and range attacks.

**Comment by Dan-Abr** [comment]
@ndvo I believe the issue is with the attacking key. Maybe the attacking key should be the same? The problem is I can still shoot while holding the knife. I'm not sure if that's intentional, but I think the player should be able to use one weapon at a time.

**Comment by ndvo** [comment]
Yup. That was intentional. The click is both changing to the range weapon
and shooting.
I think you are right, though. I'll change that behaviour so that only the
left click attacks and the right button changes weapon... or would it be
best to use other key (space? the numbers?) to change weapon?

**Comment by Dan-Abr** [comment]
Left to attack, right to change sounds good

**Comment by ndvo** [comment]
Nice! I'll work on that.

**Comment by Dan-Abr** [comment]
btw there are two of each pickup (knife x 2, gun x 2), probably because I placed the first variations under Scene-->Pickups

**Comment by ndvo** [comment]
I added the second knife and second pistol to test the inventory. Inventory is handling up to two of each Melee and Range weapon.

**Comment by Dan-Abr** [comment]
Oh okay. If possible, can you please merge feature/sunrise to this one? I saw you updated some instructions which are obsolete in my branch

**Comment by rummanwaqar** [comment]
> Oh okay. If possible, can you please merge feature/sunrise to this one? I saw you updated some instructions which are obsolete in my branch

Which ever one goes in first, the later should merge there branch with master and then make any changes. If you keep merging features in open PRs then reviews and PRs become useless because then we need to review same things in 2 places

**Comment by rummanwaqar** [comment]
@ndvo Great job man. I am going to add more guns so I will try to work off of this when it's merged

**Review by rummanwaqar — APPROVED** [review]

**Review by rummanwaqar — APPROVED** [review]
Hey what change did you make to the dog? You seem to have BulldogColor.mat + .meta & Bulldog Variant.prefab

**Pull request merged**
